### ISSUE TITLE
Missing directories on Linux Mint 14 64-bit

### ISSUE THREAD

**Issue by duncan-bayne** [earies/jvpn#2]
Before I run `jvpn` on Linux Mint 14 64-bit, I have to create the following directories:

```
~/.jvpn/cache
~/.jvpn/certs
~/.jvpn/conf
~/.jvpn/logs
```

... and touch the following file:

```
~/.jvpn/conf/jvpn.conf
```

Otherwise `jvpn` returns errors while trying to set the configuration, or download the DSID and / or certificate.

**Comment by kinow** [comment]
Same thing happened to me, on CentOS Linux release 7.2.1511 (Core)

**Comment by duncan-bayne** [comment]
Closing this; have switched to Ubuntu and FreeBSD.
